language: java
jdk:
- oraclejdk8
script: mvn clean package
notifications:
  slack:
    secure: LgE4tlYJDt/DAtD4VdrgkAGsZ2N/RYLTdJqw3NI0tU/eYPFd6BmkgKVQAMNOkXsXdKYrrSQ9v0oiiqzWxfNgkS1kZG6L6MgAnyoYEW67XLx0gwUoSSflZlOPWACvwjIrgY1QjlWs+6yfXD3Q1mSsCFKP5K9wnLJcMdX/xwiQ+GWnlFnyFadsGeF6OhOLk+rq3JeY9jMraWPkPnWwmxb9V85xshv7qBDDSn8hxwLEqvNOsV87cZ9rBd/J68dsCY3MLoiMBTh1Jeoj5F8p7CO491TRUV/PNFrUbVYCiZ8inly3BjlVTrlrG1eihgurJgvCKrXFQQ6sB3xEeNl4dlfb+rJQOOGJEer+F14c1VjSPVK6riNClv+Kwuhx+znul6bMo30U/eiAyaKfpk5iuZrRisHnCJ7h0es1g9ZeeZ1fVhPzUVxRcFSwh0QYeH/bQZl0mT7Ex/yMZHcjc5yPXANbHSkM4u/odQ+96WD4Xll9xAQCJGukY+GHB0JkNXK2gVknUdvvovPOtArdp16ydv4NhSywhLFjeWqRsLqtjp7b6VAol/+BzMfPlEarh2W19TCmPsP1D4mYfF8eRZVrry5hP6Z5kxTskxQ+n3OOIAkr9D3Y5Z+hqKf4SC3nxqYPaKnoj2+RIHoE/zpLGLAE3c2QZBIc5uK5OBVsl/q2qEaiq/U=
